#base "scheme/clientscheme_settings.res"
#base "scheme/clientscheme_borders.res"
#base "../_customizations/ENABLED/colors_custom.res"
#base "scheme/clientscheme_colors.res"
#base "../_customizations/ENABLED/Gabriel Pack/scheme/clientscheme_fonts_gabe.res"
#base "scheme/clientscheme_fonts.res"
#base "scheme/clientscheme_icons.res"
#base "scheme/clientscheme_xhairs.res"
#base "scheme/clientscheme_xhairs_outline.res"